### ISSUE TITLE
Can I add a View or Bitmap to this library?

### ISSUE THREAD

**Issue by meness** [jjhesk/LoyalNativeSlider#19]
Hi,

I'm looking for a image slider library which supports adding a view or a bitmap. Does your library support this? Thanks.

**Comment by jjhesk** [comment]
do u think u can use picasso to accomplish bitmap adding?

For view support, now you can extend the [BasicSliderView](https://github.com/jjhesk/LoyalNativeSlider/blob/master/library/src/main/java/com/hkm/slider/SliderTypes/BaseSliderView.java) like the [advancedview](https://github.com/jjhesk/LoyalNativeSlider/blob/master/library/src/main/java/com/hkm/slider/SliderTypes/AdvancedTextSliderView.java) to make your own implementations. I hope this will help.

**Comment by meness** [comment]
If you know this is a good feature, please extend it yourself, because I really don't know what have you wrote. If you can do this, please let me know. Thanks.

**Comment by jjhesk** [comment]
@alirezaaa  i will let u know once i come back to this project. thx

**Comment by jjhesk** [comment]
@alirezaaa some people like using glide and some people like it with picasso so i need to make it a generic type for people to apply with their own drawable renderer. @alirezaaa
