### ISSUE TITLE
video url feature 

### ISSUE THREAD

**Issue by 1abid** [jjhesk/LoyalNativeSlider#32]
this library really fits with my requirement excepts video feature . if the json has a url for video , is it possible to show thumbnail of the video and a video playing icon

**Comment by jjhesk** [comment]
yes. extend and modify on the BaseSliderView.

**Comment by azizimusa** [comment]
can you some example of how to load video within the slider?

**Comment by jjhesk** [comment]
if you would use the webview as the component that extends from `BaseSliderView`. This will work as the bridge to render your video url in the iframe object in html. @azizimusa @1abid [sample code which used the webview as display in a slide](https://github.com/jjhesk/LoyalNativeSlider/blob/master/weblnslider/src/main/java/com/hkm/loyalns/demos/NewsArticle.java)

**Comment by jjhesk** [comment]
video slider will have more concern on memory consumptions and leakages. However animation is supported for gif if u like to use.
