### ISSUE TITLE
replace Picasso with Glide

### ISSUE THREAD

**Issue by azizimusa** [jjhesk/LoyalNativeSlider#37]
With Picasso, large image tend to not showing on screen. I've bad experience with Picasso with my previously project. After I change to Glide, my problem solved. It would be beneficial if this plugin also use Glide.

**Comment by Mauker1** [comment]
Glide also provide SVG support.

**Comment by jjhesk** [comment]
yes i will integrate Glide in this release. thanks @azizimusa @Mauker1

**Comment by azizimusa** [comment]
UPDATE
- Need to manually extend BaseSliderView.

``` java

public class CustomSliderView extends BaseSliderView {

    public CustomSliderView(Context context) {
        super(context);
    }

    @Override
    public View getView() {
        View v = LayoutInflater.from(getContext()).inflate(com.hkm.slider.R.layout.render_type_default, null);
        ImageView target = (ImageView) v.findViewById(com.hkm.slider.R.id.ns_slider_image);
        bindEventShowGlide(v, target);
        return v;
    }

}
```

OLD QUESTION
Hi. Thanks for adding support for Glide. But how do i start using it? can't found any documentation.

**Comment by jjhesk** [comment]
yes, this is the exact implementation. thanks for the update. @azizimusa

**Comment by jjhesk** [comment]
I have found that Recently the performance for running glide isnt better than picasso. I will hold on with this library while we can mix with both libraries to get the best supports and performance.
