### ISSUE TITLE
Code example link error

### ISSUE THREAD

**Issue by firestork** [jjhesk/LoyalNativeSlider#44]
Can u check this link 
https://github.com/jjhesk/LoyalNativeSlider/blob/master/AppDemo/src/main/java/com/hkm/sliderdemo/MainActivity.java

**Comment by jjhesk** [comment]
[This should be it](https://github.com/jjhesk/LoyalNativeSlider/blob/master/weblnslider/src/main/java/com/hkm/loyalns/TheMain.java)

**Comment by firestork** [comment]
@jjhesk  thank bro
