### ISSUE TITLE
Code example

### ISSUE THREAD

**Issue by thair-jaber** [jjhesk/LoyalNativeSlider#46]
Dear,
how can view full screen image when clicking the slider?

**Comment by jjhesk** [comment]
see the example code project

**Comment by thair-jaber** [comment]
the example code  link is not working

**Comment by jjhesk** [comment]
just replace those links into something you desire

**Comment by thair-jaber** [comment]
the example code link is not working

**Comment by jjhesk** [comment]
#44 see this
