### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by pe-labs1** [jjhesk/LoyalNativeSlider#49]
I already use the mother of this library android image slider. I want to use your library cause I think it is more useful, but the problem is the demo code doesnt give me the idea how to full using it. can you give me some tutorial here?

**Comment by jjhesk** [comment]
There are steps put it very simple.
I can brief the summary of the tutorial for setting up the sliderlayout in android.
1. setup the xml 
2. implement the SliderLayout component in the fragment or activity
3. making some small adjustments 
4. setup the slider layout either by your own custom extension or using the existing provided slides from the folder SlideType
5. binding data from json or your own data providers
6. completion of the arrayList <T>, T as your data type
7. mSliderLayout.loadSliderList or .addSliderList or .addSlider independently.
8. check the result.
