### ISSUE TITLE
Conflict attributes with library

### ISSUE THREAD

**Issue by ghost** [jjhesk/LoyalNativeSlider#58]
When I imported LoyalNativeSlider into my demo app, I got this compilation error.
Of cause I could chang my attr "app_name" to another one. As a library I suggest to change attrs of LoyalNativeSlider to specific names which it's owned only. Or change application without attr.

```
Error:Gradle: Execution failed for task ':my-sample:processDebugManifest'.
> Manifest merger failed : Attribute application@label value=(@string/title_activity_main) from AndroidManifest.xml:23:9-52
    is also present at [com.hkm.loyalslider:library:1.9.4] AndroidManifest.xml:16:9-41 value=(@string/app_name).
    Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:21:5-43:19 to override.
```

**Comment by jjhesk** [comment]
if you have your own att, you can use tool replaceto override it.
